version: '3.8'
services:
  eureka-server:
    image: maxiplux/eureka-server:1.0.0
    restart: always
    privileged: true
    user: root
    environment:
      - PORT=8045
    ports:
      - 8045:8045
    container_name: eureka-server
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
  math-division-multiplication:
    image: maxiplux/math-division-multiplication:1.5.0
    restart: always
    depends_on:
      - eureka-server
      - loki
    privileged: true
    user: root
    environment:
      - PORT=8081
      - EUREKA_SERVER=eureka-server
      - SERVER_LOKI=loki:3100
    ports:
      - 8081:8081
    container_name: math-division-multiplication
  math-add-subtract:
    image: maxiplux/math-add-subtract:1.5.0
    restart: always
    privileged: true
    depends_on:
      - eureka-server
      - loki
    user: root
    environment:
      - PORT=8082
      - EUREKA_SERVER=eureka-server
      - SERVER_LOKI=loki:3100
    ports:
      - 8082:8082
    container_name: math-add-subtract

  api-gateway:
    image: maxiplux/api-gate-way:2.0.0
    restart: unless-stopped
    privileged: true
    depends_on:
      - eureka-server
      - math-add-subtract
      - math-division-multiplication
    user: root
    links:
      - eureka-server
      - math-add-subtract
      - math-division-multiplication
    environment:
      - PORT=8075
      - EUREKA_SERVER=eureka-server
      - SERVER_LOKI=loki:3100

      - SERVER_ADD_SUBTRACT=math-add-subtract
      - SERVER_ADD_SUBTRACT_PORT=8082

      - SERVER_DIVISION_MULTIPLICATION=math-division-multiplication
      - SERVER_DIVISION_MULTIPLICATION_PORT=8081

    ports:
      - 8075:8075
    container_name: api-gateway

#http://127.0.0.1:8081/swagger-ui/index.html#/home
#http://127.0.0.1:8082/swagger-ui/index.html#/home
