version: '3.8'
services:
  math-division-multiplication:
    image: maxiplux/math-division-multiplication:1.0.0
    restart: always
    privileged: true
    user: root
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    container_name: math-division-multiplication
  math-add-subtract:
    image: maxiplux/math-add-subtract:1.0.0
    restart: always
    privileged: true
    user: root
    environment:
      - PORT=8082
    ports:
      - 8082:8082
    container_name: math-add-subtract
#http://127.0.0.1:8081/swagger-ui/index.html#/home
#http://127.0.0.1:8082/swagger-ui/index.html#/home
