apiVersion: v1
kind: Service
metadata:
  name: math-add-subtract
  namespace: weclouddata
spec:
  selector:
    app: math-add-subtract
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort
