apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-division-multiplication
  namespace: weclouddata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math-division-multiplication
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
      labels:
        app: math-division-multiplication
    spec:
      containers:
      - name: math-division-multiplication
        env:
          - name: PORT
            value: "8081"
        image: maxiplux/math-division-multiplication:1.2.0
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 8081
