apiVersion: v1
kind: Service
metadata:
  name: s-math-division-multiplication
  namespace: weclouddata
spec:
  selector:
    app: math-division-multiplication
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
