apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: weclouddata
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8045
      targetPort: 8045
  type: NodePort
